language: python
python:
  - "3.6"
install:
  - pip install tox
  - python setup.py install
script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
  - {u'cli_command_name': u'imgvalidator', u'add_script': u'y'} --pytest
